"""
Faithful
"""

import csv
import math
import os
import time
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
from enum import IntEnum

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants & Enums
# ---------------------------------------------------------------------------

class ControllerLevel(IntEnum):
    """Multi-level threshold levels (Section 3.3.2)"""
    IDLE = 1       # Load < 25
    NORMAL = 2     # 25 <= Load < 50
    HIGH = 3       # 50 <= Load < 75
    OVERLOAD = 4   # Load >= 75

    @property
    def label(self):
        return {1: "Idle", 2: "Normal", 3: "High Load", 4: "Overload"}[self.value]

    @property
    def color(self):
        return {1: "#00ff88", 2: "#00d4ff", 3: "#ffaa00", 4: "#ff006e"}[self.value]


# Threshold boundaries Q[1..4]
THRESHOLDS = [25.0, 50.0, 75.0]

# Default weight coefficients (a + b + c = 1)
DEFAULT_A = 0.4   # CPU weight
DEFAULT_B = 0.3   # Memory weight
DEFAULT_C = 0.3   # Bandwidth weight

# Effectiveness threshold R — if R > θ then accept migration
EFFECTIVENESS_THRESHOLD_R = 100.0


# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------

@dataclass
class Switch:
    """A switch in the SDN data plane."""
    id: str
    controller_id: str          # Which controller domain this switch belongs to
    load_cpu: float = 0.0       # CPU load generated by this switch's Packet-In traffic
    load_mem: float = 0.0       # Memory load generated
    load_bw: float = 0.0        # Bandwidth load generated
    packet_in_rate: float = 0.0 # Packet-In messages per second
    x: float = 0.0              # Position for topology visualization
    y: float = 0.0

    def to_dict(self):
        return {
            "id": self.id,
            "controller_id": self.controller_id,
            "load_cpu": round(self.load_cpu, 3),
            "load_mem": round(self.load_mem, 3),
            "load_bw": round(self.load_bw, 3),
            "packet_in_rate": round(self.packet_in_rate, 2),
            "x": self.x,
            "y": self.y,
        }


@dataclass
class Controller:
    """An SDN controller in the control plane."""
    id: str
    capacity_cpu: float = 2000.0    # Max CPU capacity (units)
    capacity_mem: float = 4096.0    # Max Memory capacity (MB)
    capacity_bw: float = 1000.0     # Max Bandwidth capacity (Mbps)
    level: ControllerLevel = ControllerLevel.NORMAL
    load_percentage: float = 0.0     # LR_cj (0-100)
    active: bool = True
    x: float = 0.0
    y: float = 0.0

    def to_dict(self):
        return {
            "id": self.id,
            "capacity_cpu": self.capacity_cpu,
            "capacity_mem": self.capacity_mem,
            "capacity_bw": self.capacity_bw,
            "level": self.level.value,
            "level_label": self.level.label,
            "level_color": self.level.color,
            "load_percentage": round(self.load_percentage, 2),
            "active": self.active,
            "x": self.x,
            "y": self.y,
        }


@dataclass
class MigrationRecord:
    """Record of a switch migration event with full paper metrics."""
    timestamp: float
    switch_id: str
    source_controller: str
    target_controller: str
    source_load_before: float
    source_load_after: float
    target_load_before: float
    target_load_after: float
    migration_efficiency: float = 0.0
    migration_cost: float = 0.0
    imbalance_before: float = 0.0
    imbalance_after: float = 0.0
    # Paper metrics
    psi_switch: float = 0.0           # ψ(si_j)
    psi_mean: float = 0.0             # ψ̄
    rho_size: int = 0                 # |ρ| : migration set size
    domain_size: int = 0              # m : total switches in source domain
    dc_star: float = 0.0              # DC*
    dc_before_pair: float = 0.0       # DC(cj,ck) before
    dc_after_pair: float = 0.0        # DC(cj,ck) after
    theta: float = 0.0                # θ : effectiveness score
    cost_f: float = 0.0               # f(si_j, ck)
    pred_source_load: float = 0.0     # LR*_cj
    pred_target_load: float = 0.0     # LR*_ck
    target_level_star: int = 0        # C*k
    global_imbalance_before: float = 0.0
    global_imbalance_after: float = 0.0
    all_loads_before: str = ""
    all_loads_after: str = ""

    def to_dict(self):
        return {
            "timestamp": self.timestamp,
            "time_str": time.strftime("%H:%M:%S", time.localtime(self.timestamp)),
            "switch_id": self.switch_id,
            "source_controller": self.source_controller,
            "target_controller": self.target_controller,
            "source_load_before": round(self.source_load_before, 2),
            "source_load_after": round(self.source_load_after, 2),
            "target_load_before": round(self.target_load_before, 2),
            "target_load_after": round(self.target_load_after, 2),
            "migration_efficiency": round(self.migration_efficiency, 4),
            "migration_cost": round(self.migration_cost, 4),
            "imbalance_before": round(self.imbalance_before, 4),
            "imbalance_after": round(self.imbalance_after, 4),
            # Paper metrics
            "psi_switch": round(self.psi_switch, 4),
            "psi_mean": round(self.psi_mean, 4),
            "rho_size": self.rho_size,
            "domain_size": self.domain_size,
            "dc_star": round(self.dc_star, 6),
            "dc_before_pair": round(self.dc_before_pair, 6),
            "dc_after_pair": round(self.dc_after_pair, 6),
            "theta": round(self.theta, 6),
            "cost_f": round(self.cost_f, 6),
            "pred_source_load": round(self.pred_source_load, 2),
            "pred_target_load": round(self.pred_target_load, 2),
            "target_level_star": self.target_level_star,
            "global_imbalance_before": round(self.global_imbalance_before, 6),
            "global_imbalance_after": round(self.global_imbalance_after, 6),
            "all_loads_before": self.all_loads_before,
            "all_loads_after": self.all_loads_after,
        }


# ---------------------------------------------------------------------------
# DLBMT Engine
# ---------------------------------------------------------------------------

class DLBMTEngine:
    """
    Core DLBMT algorithm engine.
    Implements load calculation, multi-level thresholding, and switch migration
    selection as described in the paper.

    Aligned with the real Ryu+Mininet engine:
    - ψ-based migration cost f(si_j, ck) = ψ(si_j) × h_ik
    - DC* post-migration imbalance using global average predicted load
    - R > θ effectiveness threshold for migration acceptance
    - Global imbalance D_global = max pairwise DC
    """

    def __init__(self, a: float = DEFAULT_A, b: float = DEFAULT_B, c: float = DEFAULT_C):
        assert abs(a + b + c - 1.0) < 1e-6, "Coefficients a + b + c must equal 1"
        self.a = a
        self.b = b
        self.c = c

        self.controllers: Dict[str, Controller] = {}
        self.switches: Dict[str, Switch] = {}
        self.distance_matrix: Dict[Tuple[str, str], float] = {}  # (switch_id, ctrl_id) -> distance
        self.migration_history: List[MigrationRecord] = []
        self.load_history: List[dict] = []  # Time-series snapshots

    # -----------------------------------------------------------------------
    # Setup
    # -----------------------------------------------------------------------

    def add_controller(self, controller: Controller):
        self.controllers[controller.id] = controller

    def add_switch(self, switch: Switch):
        self.switches[switch.id] = switch

    def set_distance(self, switch_id: str, controller_id: str, distance: float):
        self.distance_matrix[(switch_id, controller_id)] = distance

    def get_distance(self, switch_id: str, controller_id: str) -> float:
        return self.distance_matrix.get((switch_id, controller_id), 1.0)

    def get_switches_in_domain(self, controller_id: str) -> List[Switch]:
        return [s for s in self.switches.values() if s.controller_id == controller_id]

    def get_active_controllers(self) -> List[Controller]:
        return [c for c in self.controllers.values() if c.active]

    # -----------------------------------------------------------------------
    # Eq. 1: Per-switch resource usage on controller  £(si, cj)
    # -----------------------------------------------------------------------

    def compute_switch_resource_usage(self, switch: Switch, controller: Controller) -> float:
        """
        Eq. 1: £_ji = a·(LoadCPU/CPU) + b·(LoadMem/Mem) + c·(LoadBw/Bw)
        Returns a value between 0 and 1.
        """
        cpu_ratio = switch.load_cpu / controller.capacity_cpu if controller.capacity_cpu > 0 else 0
        mem_ratio = switch.load_mem / controller.capacity_mem if controller.capacity_mem > 0 else 0
        bw_ratio = switch.load_bw / controller.capacity_bw if controller.capacity_bw > 0 else 0

        usage = self.a * cpu_ratio + self.b * mem_ratio + self.c * bw_ratio
        return min(usage, 1.0)

    # -----------------------------------------------------------------------
    # Eq. 7: Per-switch resource usage on TARGET controller  £ij_k
    # -----------------------------------------------------------------------

    def compute_switch_resource_on_target(self, switch: Switch, target_ctrl: Controller) -> float:
        """
        Eq. 7: £_kij = a·(LoadCPU/CPU_k) + b·(LoadMem/Mem_k) + c·(LoadBw/Bw_k)
        Resource usage of switch on the target controller (different capacity).
        """
        cpu_ratio = switch.load_cpu / target_ctrl.capacity_cpu if target_ctrl.capacity_cpu > 0 else 0
        mem_ratio = switch.load_mem / target_ctrl.capacity_mem if target_ctrl.capacity_mem > 0 else 0
        bw_ratio = switch.load_bw / target_ctrl.capacity_bw if target_ctrl.capacity_bw > 0 else 0

        usage = self.a * cpu_ratio + self.b * mem_ratio + self.c * bw_ratio
        return min(usage, 1.0)

    # -----------------------------------------------------------------------
    # Eq. 2 & 3: Controller load calculation
    # -----------------------------------------------------------------------

    def compute_controller_load(self, controller_id: str) -> float:
        """
        Eq. 2: £_j = Σ £_ji for all switches in controller's domain
        Eq. 3: LR_cj = £_j * 100
        Returns load percentage (0-100).
        """
        controller = self.controllers[controller_id]
        switches = self.get_switches_in_domain(controller_id)

        total_usage = 0.0
        for switch in switches:
            total_usage += self.compute_switch_resource_usage(switch, controller)

        load_pct = total_usage * 100.0
        return min(load_pct, 100.0)

    # -----------------------------------------------------------------------
    # Algorithm 1: Multi-level threshold
    # -----------------------------------------------------------------------

    def determine_level(self, load: float) -> ControllerLevel:
        """
        Algorithm 1: Determine controller level based on load.
        Q[1]=25, Q[2]=50, Q[3]=75
        """
        if load < THRESHOLDS[0]:
            return ControllerLevel.IDLE
        elif load < THRESHOLDS[1]:
            return ControllerLevel.NORMAL
        elif load < THRESHOLDS[2]:
            return ControllerLevel.HIGH
        else:
            return ControllerLevel.OVERLOAD

    def update_controller_levels(self) -> Dict[str, bool]:
        """
        Run Algorithm 1 for all controllers.
        Returns dict of controller_id -> whether level changed.
        """
        level_changes = {}
        for ctrl_id, ctrl in self.controllers.items():
            if not ctrl.active:
                continue
            load = self.compute_controller_load(ctrl_id)
            new_level = self.determine_level(load)
            old_level = ctrl.level

            ctrl.load_percentage = load
            ctrl.level = new_level
            level_changes[ctrl_id] = (old_level != new_level)

        return level_changes

    # -----------------------------------------------------------------------
    # Eq. 4: Migration ratio ψ(si_j) — resource-to-distance ratio
    # -----------------------------------------------------------------------

    def compute_migration_ratio(self, switch: Switch, controller: Controller) -> float:
        """
        Eq. 4: ψ(si_j) = (£(si, cj) * 100) / h_mi
        Higher ψ means the switch is resource-heavy relative to its distance.
        """
        usage = self.compute_switch_resource_usage(switch, controller)
        distance = self.get_distance(switch.id, controller.id)
        if distance < 0.001:
            distance = 0.001
        return (usage * 100.0) / distance

    # -----------------------------------------------------------------------
    # Eq. 5 & 6: Post-migration load prediction
    # -----------------------------------------------------------------------

    def compute_source_load_after_migration(self, source_ctrl: Controller,
                                             switch: Switch) -> float:
        """
        Eq. 5: LR*_cj = LR_cj - (£_ji * 100)
        """
        usage = self.compute_switch_resource_usage(switch, source_ctrl)
        return max(source_ctrl.load_percentage - (usage * 100.0), 0.0)

    def compute_target_load_after_migration(self, target_ctrl: Controller,
                                             switch: Switch) -> float:
        """
        Eq. 6: LR*_ck = LR_ck + (£_kij * 100)
        Uses target controller's capacity for the calculation.
        """
        usage_on_target = self.compute_switch_resource_on_target(switch, target_ctrl)
        return min(target_ctrl.load_percentage + (usage_on_target * 100.0), 100.0)

    # -----------------------------------------------------------------------
    # Pairwise imbalance DC(cj, ck)
    # -----------------------------------------------------------------------

    def _pairwise_imbalance(self, c1: Controller, c2: Controller) -> float:
        """
        DC(cj, ck) = |L(cj) - L(ck)| / max(L(cj), L(ck))
        Load imbalance degree between two controllers.
        """
        l1 = c1.load_percentage
        l2 = c2.load_percentage
        max_load = max(l1, l2)
        if max_load < 0.01:
            return 0.0
        return abs(l1 - l2) / max_load

    # -----------------------------------------------------------------------
    # Eq. 8: DC* — Post-migration imbalance degree
    # -----------------------------------------------------------------------

    def _dc_star(self, source: Controller, target: Controller,
                 pred_source_load: float, pred_target_load: float) -> float:
        """
        DC*(cj,ck) = ( ½·(|LR*cj - LR*| + |LR*ck - LR*|) ) / LR*
        Uses global average predicted load LR* where source and target
        loads are replaced with their post-migration predictions.
        """
        active = self.get_active_controllers()
        if not active:
            return 0.0

        # Compute LR* — global average with predicted loads substituted
        total = 0.0
        for c in active:
            if c.id == source.id:
                total += pred_source_load
            elif c.id == target.id:
                total += pred_target_load
            else:
                total += c.load_percentage
        lr_star = total / len(active)

        if lr_star < 0.01:
            return 0.0

        # RMS-style deviation from global average
        term_j = math.sqrt((pred_source_load - lr_star) ** 2)
        term_k = math.sqrt((pred_target_load - lr_star) ** 2)

        return (0.5 * (term_j + term_k)) / lr_star

    # -----------------------------------------------------------------------
    # Global imbalance D_global
    # -----------------------------------------------------------------------

    def _global_imbalance(self) -> float:
        """
        D_global = max over all pairs DC(ci, cj).
        """
        active = self.get_active_controllers()
        if len(active) < 2:
            return 0.0

        max_dc = 0.0
        for i in range(len(active)):
            for j in range(i + 1, len(active)):
                dc = self._pairwise_imbalance(active[i], active[j])
                max_dc = max(max_dc, dc)
        return max_dc

    # -----------------------------------------------------------------------
    # Eq. 10: Migration cost f(si_j, ck) — ψ-based
    # -----------------------------------------------------------------------

    def _migration_cost(self, switch: Switch, source: Controller, target: Controller) -> float:
        """
        f(si_j, ck) = ψ(si_j) × h_ik
        Migration cost = ψ(resource-to-distance ratio) × distance to target.
        """
        psi_val = self.compute_migration_ratio(switch, source)
        dist_to_target = self.get_distance(switch.id, target.id)
        return psi_val * (dist_to_target + 0.001)  # epsilon to avoid zero

    # -----------------------------------------------------------------------
    # Build migration set ρ
    # -----------------------------------------------------------------------

    def _build_migration_set(self, source: Controller):
        """
        Build migration candidate set ρ.
        1. Compute ψ for each switch in source's domain
        2. Compute mean ψ̄ = (1/m) × Σψ
        3. Only switches with ψ >= ψ̄ enter ρ

        Returns: (rho, psi_values, psi_mean, domain_size)
        """
        dom_switches = self.get_switches_in_domain(source.id)

        if not dom_switches:
            return [], {}, 0.0, 0

        # Compute ψ per switch
        psi_values: Dict[str, float] = {}
        psi_sum = 0.0
        for sw in dom_switches:
            psi_val = self.compute_migration_ratio(sw, source)
            psi_values[sw.id] = psi_val
            psi_sum += psi_val

        # ψ̄ = (1/m) × Σψ
        m = len(dom_switches)
        psi_mean = psi_sum / m

        # Only switches with ψ >= ψ̄ enter ρ
        rho = [sw for sw in dom_switches if psi_values[sw.id] >= psi_mean]

        logger.debug("Migration set ρ for %s: %d / %d switches (ψ̄=%.3f)",
                      source.id, len(rho), m, psi_mean)
        return rho, psi_values, psi_mean, m

    # -----------------------------------------------------------------------
    # Algorithm 2: Find best migration candidate for a source controller
    # -----------------------------------------------------------------------

    def _find_best_migration(self, source: Controller):
        """
        Select optimal (switch, target_controller) pair.
        1. Build migration set ρ (filter by ψ ≥ ψ̄)
        2. For each switch in ρ, predict post-migration loads, reclassify target, compute DC*
        3. Select (switch, target) pair that minimizes DC*, with target remaining IDLE or NORMAL
        4. Compute effectiveness θ, select if R > θ
        """
        # Build migration set ρ
        rho, psi_values, psi_mean, domain_size = self._build_migration_set(source)
        if not rho:
            logger.debug("Empty migration set ρ for %s", source.id)
            return None

        # Candidate targets: all active controllers except source
        all_targets = [c for c in self.controllers.values()
                       if c.active and c.id != source.id]

        if not all_targets:
            return None

        # Evaluate all (switch, target) pairs
        candidates = []
        for sw in rho:
            sw_usage_on_source = self.compute_switch_resource_usage(sw, source)
            for tgt in all_targets:
                sw_usage_on_target = self.compute_switch_resource_on_target(sw, tgt)

                # LR*_cj = LR_cj - (£_ji × 100)
                pred_source_load = max(source.load_percentage - sw_usage_on_source * 100, 0)

                # LR*_ck = LR_ck + (£ij_k × 100)
                pred_target_load = min(tgt.load_percentage + sw_usage_on_target * 100, 100)

                # Reclassify target
                target_level_star = self.determine_level(pred_target_load)

                # Compute DC*
                dc_star = self._dc_star(source, tgt, pred_source_load, pred_target_load)

                # Current pairwise imbalance DC (for θ computation)
                dc_before = self._pairwise_imbalance(source, tgt)

                candidates.append({
                    "switch": sw,
                    "target": tgt,
                    "dc_star": dc_star,
                    "dc_before": dc_before,
                    "pred_src": pred_source_load,
                    "pred_tgt": pred_target_load,
                    "target_level_star": target_level_star,
                })

        if not candidates:
            return None

        # Only consider targets where C*k == IDLE(1) or NORMAL(2)
        valid_candidates = [
            c for c in candidates
            if c["target_level_star"] in (ControllerLevel.IDLE, ControllerLevel.NORMAL)
        ]

        if not valid_candidates:
            if source.level == ControllerLevel.OVERLOAD:
                logger.warning(
                    "Controller %s is OVERLOADED but no valid migration target. "
                    "A controller should be added.", source.id
                )
            else:
                logger.debug("No valid migration for %s (level=%s)",
                             source.id, source.level.label)
            return None

        # Find candidate with minimum DC*
        best_dc_candidate = min(valid_candidates, key=lambda c: c["dc_star"])

        # Compute effectiveness: θ = |DC* - DC(cj,ck)| / f(si_j, ck)
        sw = best_dc_candidate["switch"]
        tgt = best_dc_candidate["target"]
        dc_star = best_dc_candidate["dc_star"]
        dc_before = best_dc_candidate["dc_before"]

        cost = self._migration_cost(sw, source, tgt)
        if cost < 0.001:
            cost = 0.001

        theta = abs(dc_star - dc_before) / cost

        # If R > θ then select SC
        if EFFECTIVENESS_THRESHOLD_R > theta:
            logger.info(
                "Selected migration %s → %s (DC*=%.4f, θ=%.4f, R=%.1f)",
                sw.id, tgt.id, dc_star, theta, EFFECTIVENESS_THRESHOLD_R
            )

            return (sw, tgt, theta, {
                "cost": cost,
                "efficiency": theta,
                "pred_src": best_dc_candidate["pred_src"],
                "pred_tgt": best_dc_candidate["pred_tgt"],
                "dc_before": dc_before,
                "dc_star": dc_star,
                "src_load_before": source.load_percentage,
                "tgt_load_before": tgt.load_percentage,
                # Evaluation metrics
                "psi_switch": psi_values.get(sw.id, 0.0),
                "psi_mean": psi_mean,
                "rho_size": len(rho),
                "domain_size": domain_size,
                "theta": theta,
                "cost_f": cost,
                "target_level_star": best_dc_candidate["target_level_star"].value,
            })

        logger.debug("Effectiveness θ=%.4f exceeds R=%.1f, migration rejected",
                      theta, EFFECTIVENESS_THRESHOLD_R)
        return None

    # -----------------------------------------------------------------------
    # Execute migration
    # -----------------------------------------------------------------------

    def _execute_migration(self, switch: Switch, source_ctrl: Controller,
                           target_ctrl: Controller, data: dict) -> MigrationRecord:
        """Execute the switch migration and record it with full paper metrics."""
        dc_before = data.get("dc_before", 0)

        # Capture global imbalance BEFORE migration
        global_imb_before = self._global_imbalance()
        loads_before = {c.id: round(c.load_percentage, 2)
                        for c in self.controllers.values() if c.active}

        # Perform migration
        switch.controller_id = target_ctrl.id

        # Recalculate loads
        self.update_controller_levels()

        dc_after = self._pairwise_imbalance(source_ctrl, target_ctrl)
        global_imb_after = self._global_imbalance()
        loads_after = {c.id: round(c.load_percentage, 2)
                       for c in self.controllers.values() if c.active}

        record = MigrationRecord(
            timestamp=time.time(),
            switch_id=switch.id,
            source_controller=source_ctrl.id,
            target_controller=target_ctrl.id,
            source_load_before=data.get("src_load_before", source_ctrl.load_percentage),
            source_load_after=source_ctrl.load_percentage,
            target_load_before=data.get("tgt_load_before", target_ctrl.load_percentage),
            target_load_after=target_ctrl.load_percentage,
            migration_efficiency=data.get("efficiency", 0),
            migration_cost=data.get("cost", 0),
            imbalance_before=dc_before,
            imbalance_after=dc_after,
            # Paper metrics
            psi_switch=data.get("psi_switch", 0),
            psi_mean=data.get("psi_mean", 0),
            rho_size=data.get("rho_size", 0),
            domain_size=data.get("domain_size", 0),
            dc_star=data.get("dc_star", 0),
            dc_before_pair=dc_before,
            dc_after_pair=dc_after,
            theta=data.get("theta", 0),
            cost_f=data.get("cost_f", 0),
            pred_source_load=data.get("pred_src", 0),
            pred_target_load=data.get("pred_tgt", 0),
            target_level_star=data.get("target_level_star", 0),
            global_imbalance_before=global_imb_before,
            global_imbalance_after=global_imb_after,
            all_loads_before=str(loads_before),
            all_loads_after=str(loads_after),
        )

        self.migration_history.append(record)
        self._write_eval_csv(record)

        logger.info(
            "Migration: %s %s→%s  DC: %.4f → %.4f  D_global: %.4f → %.4f",
            switch.id, source_ctrl.id, target_ctrl.id,
            dc_before, dc_after, global_imb_before, global_imb_after
        )
        return record

    # -----------------------------------------------------------------------
    # Algorithm 2: Load Balancing (Full)
    # -----------------------------------------------------------------------

    def run_load_balancing(self) -> Optional[MigrationRecord]:
        """
        Algorithm 2: Complete load balancing algorithm.

        1. Update all controller levels
        2. Find controllers in HIGH or OVERLOAD state
        3. For each, find the best migration candidate (min DC*, R > θ)
        4. Select globally best migration across all sources
        5. Execute single greedy migration per cycle
        """
        # Step 1: Update levels
        self.update_controller_levels()

        # Trigger for HIGH (3) or OVERLOAD (4)
        sources = [c for c in self.controllers.values()
                   if c.active
                   and c.level in (ControllerLevel.HIGH, ControllerLevel.OVERLOAD)]

        if not sources:
            return None

        # Find the globally best migration across all source controllers
        best_pair = None
        best_dc_star = float("inf")

        for src in sources:
            result = self._find_best_migration(src)
            if result:
                sw, tgt, theta, record_data = result
                dc_star = record_data.get("dc_star", float("inf"))
                if dc_star < best_dc_star:
                    best_dc_star = dc_star
                    best_pair = (sw, src, tgt, record_data)

        if best_pair:
            return self._execute_migration(*best_pair)

        logger.info("No suitable migration found for any overloaded controller")
        return None

    # -----------------------------------------------------------------------
    # CSV Evaluation Log
    # -----------------------------------------------------------------------

    _CSV_FILE = "logs.csv"
    _CSV_HEADERS = [
        "timestamp", "time_str", "migration_#",
        "switch", "source", "target",
        "src_load_before", "src_load_after",
        "tgt_load_before", "tgt_load_after",
        "pred_src_load", "pred_tgt_load",
        "psi_switch", "psi_mean", "rho_size", "domain_size",
        "DC_before", "DC_star", "DC_after",
        "theta", "cost_f", "R_threshold",
        "target_C_star",
        "global_imb_before", "global_imb_after",
        "all_loads_before", "all_loads_after",
    ]

    def _write_eval_csv(self, rec: MigrationRecord):
        csv_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), self._CSV_FILE)
        file_exists = os.path.isfile(csv_path)
        try:
            with open(csv_path, "a", newline="") as f:
                w = csv.writer(f)
                if not file_exists:
                    w.writerow(self._CSV_HEADERS)

                level_names = {1: "IDLE", 2: "NORMAL", 3: "HIGH", 4: "OVERLOAD"}
                w.writerow([
                    round(rec.timestamp, 3),
                    time.strftime("%H:%M:%S", time.localtime(rec.timestamp)),
                    len(self.migration_history),
                    rec.switch_id,
                    rec.source_controller,
                    rec.target_controller,
                    round(rec.source_load_before, 2),
                    round(rec.source_load_after, 2),
                    round(rec.target_load_before, 2),
                    round(rec.target_load_after, 2),
                    round(rec.pred_source_load, 2),
                    round(rec.pred_target_load, 2),
                    round(rec.psi_switch, 4),
                    round(rec.psi_mean, 4),
                    rec.rho_size,
                    rec.domain_size,
                    round(rec.dc_before_pair, 6),
                    round(rec.dc_star, 6),
                    round(rec.dc_after_pair, 6),
                    round(rec.theta, 6),
                    round(rec.cost_f, 6),
                    EFFECTIVENESS_THRESHOLD_R,
                    level_names.get(rec.target_level_star, "?"),
                    round(rec.global_imbalance_before, 6),
                    round(rec.global_imbalance_after, 6),
                    rec.all_loads_before,
                    rec.all_loads_after,
                ])
        except Exception as e:
            logger.error("Failed to write eval CSV: %s", e)

    # -----------------------------------------------------------------------
    # Snapshot for time-series
    # -----------------------------------------------------------------------

    def take_snapshot(self) -> dict:
        """Capture current state for time-series tracking."""
        active = self.get_active_controllers()
        avg_load = sum(c.load_percentage for c in active) / len(active) if active else 0

        snapshot = {
            "timestamp": time.time(),
            "controllers": {c.id: {
                "load": round(c.load_percentage, 2),
                "level": c.level.value,
                "level_label": c.level.label,
                "level_color": c.level.color,
            } for c in active},
            "avg_load": round(avg_load, 2),
            "global_imbalance": round(self._global_imbalance(), 4),
            "total_switches": len(self.switches),
            "total_migrations": len(self.migration_history),
        }
        self.load_history.append(snapshot)

        # Keep only last 300 snapshots (5 min at 1/sec)
        if len(self.load_history) > 300:
            self.load_history = self.load_history[-300:]

        return snapshot

    def get_stats(self) -> dict:
        """Get comprehensive stats for the dashboard."""
        active = self.get_active_controllers()
        avg_load = sum(c.load_percentage for c in active) / len(active) if active else 0

        # Controller domain sizes
        domain_sizes = {}
        for ctrl in active:
            domain_sizes[ctrl.id] = len(self.get_switches_in_domain(ctrl.id))

        return {
            "avg_load": round(avg_load, 2),
            "global_imbalance": round(self._global_imbalance(), 4),
            "total_controllers": len(active),
            "total_switches": len(self.switches),
            "total_migrations": len(self.migration_history),
            "domain_sizes": domain_sizes,
            "controller_loads": {c.id: round(c.load_percentage, 2) for c in active},
            "controller_levels": {c.id: c.level.label for c in active},
        }